// catalogus.js
const catalogus = [
  {
    id: 'tshirt-001',
    naam: 'Half-Zip Turtleneck',
    merk: '"2005"',
    prijs: 49.95,
    afbeelding: 'https://img.ltwebstatic.com/images3_spmp/2025/01/17/06/1737104830312c162ddc995c44004eb3f06d4511c9.webp',
    kleur: 'Wit',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#shirts'],
    gender: 'men',
    flavour: "Our designers have been working hard to design something classic, comfortable and stylish. This Half-Zip Turtleneck is made from soft, breathable fabric that keeps you warm without overheating. Perfect for those venturing out on chilly days or layering under your favorite jacket. with a sterling silver star zipper detail, this turtleneck adds a touch of sophistication to your casual wardrobe.",
  },
  {
    id: 'hoodie-101',
    naam: 'Comfort Hoodie',
    merk: '"2005"',
    prijs: 49.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/pi/2025/12/24/f6/1766540933364d0ad8641d16a9124e3c80c21f2070.webp',
    kleur: 'Zwart',
    maten: ['S', 'M', 'L'],
    tag: ['#sweaters', '#jackets'],
    gender: 'women',
    flavour: "U wanna be a baddie? That takes time and comfort but our best designers have worked hard to give you back your comfort. This Comfort Hoodie is made from soft, breathable fabric that keeps you warm without overheating. Perfect for those venturing out on chilly days or layering under your favorite jacket. with a sterling silver star zipper detail, this hoodie adds a touch of sophistication to your casual wardrobe.",
  },
  {
    id: 'sweatpants-201',
    naam: 'Printed Sweatpants',
    merk: '"2005"',
    prijs: 59.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/pi/2025/10/06/5c/1759761738481ca5b3aa9e3116a6534fa6bce31270.webp',
    kleur: 'Indigo',
    maten: ['30', '32', '34', '36'],
    tag: ['#pants'],
    gender: 'unisex',
    flavour: "Rock the room wherever you go with a design so iconic, comfortable and stylish it's an extention of yourself. Angelic graphics adorn these Printed Sweatpants made from soft, breathable cotton that keeps you comfortable all day long. Be sick as **** lounging at home.",
  },
  {
    id: 'dress-301',
    naam: 'Knit Striped Dress',
    merk: '"2005"',
    prijs: 59.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/pi/2025/10/14/7d/176043583858d0f6ea351304da96e8dc4828d50284.webp',
    kleur: 'Bloemen',
    maten: ['XS', 'S', 'M', 'L'],
    tag: ['#dresses'],
    gender: 'women',
    flavour: "Make a statement wherever you go with a design so iconic, comfortable and stylish it's an extention of yourself. This Knit Striped Dress is made from soft, breathable wool that keeps you warm. It's an iconic 2005 piece that combines comfort and style effortlessly as always.",
  },
  {
    id: 'crocs-401',
    naam: 'Chrome PlatformCrocs',
    merk: '"2005"',
    prijs: 79.95,
    afbeelding: 'https://img.ltwebstatic.com/images3_spmp/2024/11/12/1b/1731378780cd08489ac6a130f2efd7effb63a69b90.webp',
    kleur: 'Wit/Zwart',
    maten: ['38', '39', '40', '41', '42', '43', '44'],
    tag: ['#shoes'],
    gender: 'women',
    flavour: "Step into the future with a design so BOLD that every step is an earthquake. These black Platform Crocs are made from soft, durable material that keeps your feet protected all day long inside or outside. Perfect for casual outings or making a bold fashion statement together with a sterling silver details, these crocs will make you gnarly wherever you go.",
  },
  {
    id: 'jacket-501',
    naam: 'Furry Sweat Jacket',
    merk: '"2005"',
    prijs: 49.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/pi/2025/12/31/4a/17671739061395465b80681f0af3d724fb3db77974.webp',
    kleur: 'Black',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#sweaters', '#jackets'],
    gender: 'unisex',
    flavour: "Sweater? Vest? Jacket? Fur? Why not all of them combined into one iconic piece? Kinda like mans shampoo this Furry sweat jacket has it all. Made from cotton and with faux fur on the hood, we will make you stand out in the snow. Perfect to pair with our iconic printed sweat pants and shoes for that full 2005 look.",
  },
  {
    id: 'sweater-321',
    naam: 'Wavy Sweater',
    merk: '"2005"',
    prijs: 49.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/pi/2025/11/25/45/17640335995a9293aae99adadd01448610e47a5bb4.webp',
    kleur: 'Gray',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#sweaters'],
    gender: 'men',
    flavour: "MEN! Homies! Bros! chillout and get wavy with it our designers heard you plea for something less and less is more right? Wave your boring collection goodbye and groove into something smooth and stylish. Made from soft cotton and wool. YES you heard it right WOOL AND COTTON. Stay warm and stylish this winter with our Wavy Sweater.",
  },
  {
    id: 'pants-211',
    naam: 'Leather Cargos',
    merk: '"2005"',
    prijs: 69.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/pi/2025/07/28/ca/1753687711ba79d80d3e64b7ecbc11728af00c3703_thumbnail_900x.webp',
    kleur: 'Blauw',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#pants'],
    gender: 'men',
    flavour: "Get ready to turn heads with our Leather Cargos, the ultimate blend of edgy style and comfort. Crafted from high-quality faux leather, these cargos are designed to make a bold statement wherever you go. With multiple pockets and a relaxed fit, they offer both functionality and fashion. Whether you're hitting the streets or heading to a casual hangout, these cargos will keep you looking fresh and feeling comfortable all day long.",
  },
  {
    id: 'belt-411',
    naam: 'Chromestar Belt',
    merk: '"2005"',
    prijs: 39.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/spmp/2025/04/18/e8/17449718765f9299028c3a9bf0eac65f5b478e34ca.webp',
    kleur: 'Blauw',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#accessories'],
    gender: 'unisex',
    flavour: "Elevate your outfit with our Chromestar Belt, the perfect accessory to add a touch of shine and sophistication to any look. Crafted from durable pvc leather and sterling silver, this belt features a sleek star buckle that catches the light and draws attention. Whether you're dressing up for a night out or adding flair to your everyday attire, the Chromestar Belt is designed to complement your style while providing a comfortable fit. Make a statement and let your waist do the talking with this iconic accessory.",
  },
  {
    id: 'tee-701',
    naam: 'Printed Anime Tee',
    merk: '"2005"',
    prijs: 49.95,
    afbeelding: 'https://img.ltwebstatic.com/images3_pi/2024/04/19/0e/171349249834f6ee6ca1cc5d3640ff24a59a55d0f6.webp',
    kleur: 'Blauw',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#shirts'],
    gender: 'unisex',
    flavour: "Wassup NERD! yes you! the customer who's reading this. w e   a r e   w a t c h i n g   y o u . And we see you love anime. So do we! That's why we designed this Printed Anime Tee just for you. Made from soft, breathable cotton, this tee features vibrant anime graphics that showcase your passion for the genre. Whether you're attending a convention or just hanging out with friends, this tee is perfect for expressing your love for all things anime in style and comfort.",
  },
  {
    id: 'jacket-901',
    naam: 'Chillie Jacket',
    merk: '"2005"',
    prijs: 129.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/pi/2025/09/01/60/17566913516fa7e205258d7f6511e7373ad5b5141f.webp',
    kleur: 'Zwart',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#jackets'],
    gender: 'unisex',
    flavour: "Run, no OWN the runway with one of our less popular but ever bolder ideas. Trully combining y2k with avantgarde thinking. This Chillie Jacket is made from high-quality materials (mainly denim) that provide warmth and protection against the elements. Its unique design features bold colors and patterns that make a statement wherever you go. Whether you're braving the cold or just want to stand out in a crowd, this jacket is sure to turn heads and keep you cozy all season long.",

  },
  {
    id: 'pants-811',
    naam: 'Holy Jeans',
    merk: '"2005"',
    prijs: 69.95,
    afbeelding: 'https://img.ltwebstatic.com/v4/j/pi/2025/10/27/63/176153214377d84ed690a61f809b99a08e9acff533.webp',
    kleur: 'Blauw',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#pants'],
    gender: 'unisex',
    flavour: "Heaven called they want their pants back. But we said NO! These denim jeans with crossed patched on the knees made from other denim jeans (denim on denim) are here to stay. Rock these Holy Jeans and feel the divine comfort and style that comes with them. Perfect for casual outings or dressing up for a night out, these jeans will make you feel like you're walking on clouds.",
  },
  {
    id: 'belt-601',
    naam: 'X-Star Belt',
    merk: '"2005"',
    prijs: 39.95,
    afbeelding: 'https://y2kdream.com/cdn/shop/files/Y2K-Cross-Star-Buckle-Leather-Belt-2.webp?v=1737621873&width=1000',
    kleur: 'Blauw',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#accessories'],
    gender: 'unisex',
    flavour: "Hey you a x-man or something? No? Well still rock this X-Star Belt like a baddass and feel the power of the iconic cross star buckle. Made from durable leather and sterling silver, this belt is designed to provide a comfortable fit while adding a touch of edge to your outfit. Whether you're dressing up for a night out or just want to add some flair to your everyday look, the X-Star Belt is the perfect accessory to complete your ensemble.",
  },
  {
    id: 'sneakers-701',
    naam: 'Skywalker - Cloud Runners',
    merk: '"2005"',
    prijs: 89.95,
    afbeelding: 'https://ae01.alicdn.com/kf/S18b422bd3b85405780e88326cbee362aL.jpg',
    kleur: 'Wit/Blauw',
    maten: ['38', '39', '40', '41', '42', '43', '44'],
    tag: ['#shoes'],
    gender: 'unisex',
    flavour: "WHAT ARE THOSE!!!! they're 2005 skywalkers? These Cloud Runners are designed to give you the ultimate comfort and style. Made from lightweight materials, these sneakers provide a cushioned sole that feels like you're walking on clouds and they kinda look like the sky and clouds. Perfect for everyday wear or hitting the gym, these shoes will keep you comfortable and looking fresh all day long.",
  },
  {
    id: 'sneakers-702',
    naam: 'Skywalker - Chrome Runners',
    merk: '"2005"',
    prijs: 89.95,
    afbeelding: 'https://static.nike.com/a/images/t_web_pw_592_v2/f_auto/a814995d-a806-4c82-9c1f-7cd2361a8bb6/AIR+ZOOM+SPIRIDON+CAGE+2.png',
    kleur: 'Wit/Neon Groen',
    maten: ['38', '39', '40', '41', '42', '43', '44'],
    tag: ['#shoes'],
    gender: 'unisex',
    flavour: "feeling sporty? wanna run like the wind? Our Skywalker - Chrome Runners are designed to give you the ultimate comfort and style. Made from lightweight materials, these sneakers provide a cushioned sole that feels like you're walking on clouds. Perfect for everyday wear or hitting the gym, these shoes will keep you comfortable and looking fresh all day long.",
  },
  {
    id: 'Boots-702',
    naam: 'Covered Boots',
    merk: '"2005"',
    prijs: 139.95,
    afbeelding: 'https://www.net-a-porter.com/variants/images/46376663162964819/in/w2000_q60.jpg',
    kleur: 'black',
    maten: ['38', '39', '40', '41', '42', '43', '44'],
    tag: ['#shoes'],
    gender: 'women',
    flavour: "Girl you know you wanna be bold and different right? You want to SLAY! Our Covered Boots are designed to give you that edgy and stylish look you've been craving. Made from high-quality leather, these boots provide both comfort and durability. Perfect for making a fashion statement, these boots will elevate any outfit and keep you looking fierce all day long.",
  },
  {
    id: 'dress-302',
    naam: 'knit Belted dress',
    merk: '"2005"',
    prijs: 79.95,
    afbeelding: 'https://i.pinimg.com/736x/c0/76/74/c07674e6a5baedab3b9790b28ab66f5f.jpg',
    kleur: 'Wit/Blauw',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#dresses'],
    gender: 'women',
    flavour: "This knit Belted dress is the perfect blend of comfort and style. Made from high-quality materials, it features a belted waist and wrists that flatters your figure and a cozy knit texture that keeps you warm. Whether you're heading to a casual brunch or a more formal event, this dress will keep you looking elegant and feeling comfortable. (wearable with or without belts)",
  },
  {
    id: 'jacket-902',
    naam: 'Cropped Star Vest',
    merk: '"2005"',
    prijs: 89.95,
    afbeelding: 'https://media.discordapp.net/attachments/1091790867548876972/1461834933243875500/294f329783efb9762a71be53d74ddd48.png?ex=696f4b1f&is=696df99f&hm=ce200dac3fe15c6ad33dbe4e0da48c67b14d5cdde1715d0f6a276862f7c64fef&=&format=webp&quality=lossless&width=1660&height=2034',
    kleur: 'Zwart',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#jackets', '#vests'],
    gender: 'women',
    flavour: "Stay warm and stylish with our puffy Cropped Star Vest, the perfect layering option for any winter outfit that needs to be less. Because less is more. Made from high-quality materials, this vest features a cropped design that adds a trendy touch to your look while keeping your core warm. Whether you're heading out for a casual day or dressing up for a night out, this vest is sure to elevate your style and keep you cozy all season long.",
  },
  {
    id: 'sweater-501',
    naam: 'Turleneck Star Sweater',
    merk: '"2005"',
    prijs: 59.95,
    afbeelding: 'https://media.discordapp.net/attachments/1091790867548876972/1461834964302692545/af570ef8c9c3bd7ff3cb38d099c1e90b.png?ex=696f4b27&is=696df9a7&hm=406e09d4fed52c0440aa261695e7c09bc89cd0e705a882349ef7de16051c51f3&=&format=webp&quality=lossless&width=1526&height=2034',
    kleur: 'Wit',
    maten: ['S', 'M', 'L', 'XL'],
    tag: ['#sweaters'],
    gender: 'women',
    flavour: "Sleeveless, Warm, Turtleneck and Stylish. You thought it was impossible? Our designers thought the same until they created this iconic Turtleneck Star Sweater. Made from soft, durable and exceptionally warm fabric, this sweater keeps you warm without overheating. Perfect for layering under your favorite jacket or wearing on its own, this turtleneck adds a touch of sophistication to your casual wardrobe.",
  },
  {
    id: 'boots-703',
    naam: 'Leather Knee Boots',
    merk: '"2005"',
    prijs: 149.95,
    afbeelding: 'https://i.pinimg.com/736x/c8/f9/48/c8f94848bde48bed210c7bb506c52858.jpg',
    kleur: 'Zwart',
    maten: ['38', '39', '40', '41', '42', '43', '44'],
    tag: ['#shoes', '#boots'],
    gender: 'women',
    flavour: "Step up your fashion game with our Leather Knee Boots adorned with cute bows, the perfect combination of edgy and feminine style. Made from high-quality leather, these boots provide both comfort and durability. The knee-high design adds a touch of sophistication to any outfit, while the bow details bring a playful and charming element. Whether you're dressing up for a night out or adding flair to your everyday look, these boots will keep you looking fierce and fabulous all day long.",
  }
];

module.exports = catalogus;
